---

- hosts: all
  become: true
  tasks:

  - name: install apache with php support
    package:
      name: 
        - apache2
        - libapache2_mod_php
      state: latest
      update_cache: yes
      when: ansible_distribution == "Ubuntu"

  - name: install apache with php support
    package:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
      when: ansible_distribution == "CentOS"
